# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.
